In [8]:
import pandas as pd
df = pd.read_csv('netflix_titles.csv')

In [9]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [11]:
# Load the data into SQL Server using the replace option
import sqlalchemy as sal

# Fix the connection string
engine = sal.create_engine(r'mssql://MISIANI-PC\MSSQLSERVER01/master?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')

# Connect to the database
conn = engine.connect()

In [12]:
#load the data into sql server using append option
df.to_sql('netflix_shows', con=conn , index=False, if_exists = 'append')

IntegrityError: (pyodbc.IntegrityError) ('23000', "[23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Violation of PRIMARY KEY constraint 'PK__NetflixS__2B97D71C2E297B37'. Cannot insert duplicate key in object 'dbo.netflix_shows'. The duplicate key value is (s55). (2627) (SQLExecDirectW); [23000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated. (3621)")
[SQL: INSERT INTO netflix_shows (show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?,  ... 6409 characters truncated ...  ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('s1', 'Movie', 'Dick Johnson Is Dead', 'Kirsten Johnson', None, 'United States', 'September 25, 2021', 2020, 'PG-13', '90 min', 'Documentaries', 'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.', 's2', 'TV Show', 'Blood & Water', None, 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mah ... (5 characters truncated) ... , Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng', 'South Africa', 'September 24, 2021', 2021, 'TV-MA', '2 Seasons', 'International TV Shows, TV Dramas, TV Mysteries', 'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.', 's3', 'TV Show', 'Ganglands', 'Julien Leclercq', 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera', None, 'September 24, 2021', 2021, 'TV-MA', '1 Season', 'Crime TV Shows, International TV Shows, TV Action & Adventure', 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.', 's4', 'TV Show', 'Jailbirds New Orleans', None, None, None, 'September 24, 2021', 2021, 'TV-MA', '1 Season', 'Docuseries, Reality TV', 'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.', 's5', 'TV Show' ... 1988 parameters truncated ... 'Action & Adventure, Dramas', "A tidal wave spells disaster for a ship of New Year's Eve revelers when it capsizes the mammoth vessel, sending passengers into a battle for survival.", 's171', 'Movie', 'Rhyme & Reason', 'Peter Spirer', 'Too $hort, B-Real, Kurtis Blow, Da Brat, Grandmaster Caz, Sean "P. Diddy" Combs, Chuck D., Desiree Densiti, Dr. Dre, E-40, MC Eiht, Heavy D, Lauryn H ... (118 characters truncated) ... The Notorious B.I.G., Master P, Q-Tip, Raekwon, Redman, Senen Reyes, Busta Rhymes, RZA, DJ Scratch, Erick Sermon, Tupac Shakur, Adario Strange, Suave', 'United States', 'September 1, 2021', 1997, 'R', '89 min', 'Documentaries, Music & Musicals', 'The world and culture of rap song topics such as race, violence, police, family and sex are examined by hip-hop performers from both coasts.', 's172', 'Movie', 'Same Kind of Different as Me', 'Michael Carney', 'Greg Kinnear, RenÃ©e Zellweger, Djimon Hounsou, Jon Voight, Olivia Holt', 'United States', 'September 1, 2021', 2017, 'PG-13', '120 min', 'Dramas, Faith & Spirituality', 'A wealthy couple whose marriage is on the rocks befriends a local homeless man who changes their perspectives in this inspiring true story.', 's173', 'Movie', 'School of Rock', 'Richard Linklater', 'Jack Black, Joan Cusack, Mike White, Sarah Silverman, Lee Wilkof, Kate McGregor-Stewart, Adam Pascal, Suzzanne Douglas, Miranda Cosgrove, Kevin Alexander Clark, Joey Gaydos Jr., Robert Tsai, Veronica Afflerbach, Jordan-Claire Green', 'United States, Germany', 'September 1, 2021', 2003, 'PG-13', '110 min', 'Comedies, Music & Musicals', "Musician Dewey Finn gets a job as a fourth-grade substitute teacher, where he secretly begins teaching his students the finer points of rock 'n' roll.", 's174', 'Movie', 'Snervous Tyler Oakley', 'Amy Rice', 'Tyler Oakley', 'United States', 'September 1, 2021', 2015, 'PG-13', '83 min', 'Documentaries, LGBTQ Movies', 'The inspiring Internet star and LGBT advocate shares an intimate view of his life and relationships during his international "Slumber Party" tour.')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
df